/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import com.mycompany.views.Accommodations;
import com.mycompany.views.Principal;
import com.mycompany.views.Reports;
import com.mycompany.views.Reservations;
import com.mycompany.views.Users;
import java.awt.BorderLayout;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JPanel;

/**
 *
 * @author zerot
 */
public class Dashboard extends javax.swing.JFrame {

    int xMouse, yMouse;
    public Dashboard() {
        initComponents();
        SetDate();
        InitContent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void InitContent() {
        ShowJPanel(new Principal());
    }
    
    public static void ShowJPanel(JPanel p) {
        p.setSize(750, 460);
        p.setLocation(0,0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Principal = new javax.swing.JPanel();
        Principalbtn = new javax.swing.JButton();
        Hospedaje = new javax.swing.JPanel();
        hospedaje = new javax.swing.JButton();
        Reservaciones = new javax.swing.JPanel();
        reservaciones = new javax.swing.JButton();
        Usuarios = new javax.swing.JPanel();
        usuarios = new javax.swing.JButton();
        Reportes = new javax.swing.JPanel();
        reportes = new javax.swing.JButton();
        Header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dateText = new javax.swing.JLabel();
        Headerbar = new javax.swing.JPanel();
        Exitpanel = new javax.swing.JPanel();
        Exitxt = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setPreferredSize(new java.awt.Dimension(1020, 640));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(13, 71, 161));
        Menu.setPreferredSize(new java.awt.Dimension(270, 640));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hotel");
        Menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, 258, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        Menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 79, 180, 15));

        Principal.setBackground(new java.awt.Color(21, 101, 192));
        Principal.setLayout(new java.awt.BorderLayout());

        Principalbtn.setBackground(new java.awt.Color(21, 101, 192));
        Principalbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Principalbtn.setForeground(new java.awt.Color(255, 255, 255));
        Principalbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/home-outline.png"))); // NOI18N
        Principalbtn.setText("Principal");
        Principalbtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        Principalbtn.setBorderPainted(false);
        Principalbtn.setContentAreaFilled(false);
        Principalbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Principalbtn.setFocusPainted(false);
        Principalbtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Principalbtn.setIconTextGap(10);
        Principalbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PrincipalbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PrincipalbtnMouseExited(evt);
            }
        });
        Principalbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrincipalbtnActionPerformed(evt);
            }
        });
        Principal.add(Principalbtn, java.awt.BorderLayout.CENTER);

        Menu.add(Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 270, 60));

        Hospedaje.setBackground(new java.awt.Color(21, 101, 192));
        Hospedaje.setMinimumSize(new java.awt.Dimension(108, 30));
        Hospedaje.setLayout(new java.awt.BorderLayout());

        hospedaje.setBackground(new java.awt.Color(21, 101, 192));
        hospedaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hospedaje.setForeground(new java.awt.Color(255, 255, 255));
        hospedaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/calendar-plus.png"))); // NOI18N
        hospedaje.setText("Hospedaje");
        hospedaje.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        hospedaje.setBorderPainted(false);
        hospedaje.setContentAreaFilled(false);
        hospedaje.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hospedaje.setFocusPainted(false);
        hospedaje.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        hospedaje.setIconTextGap(10);
        hospedaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hospedajeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hospedajeMouseExited(evt);
            }
        });
        hospedaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospedajeActionPerformed(evt);
            }
        });
        Hospedaje.add(hospedaje, java.awt.BorderLayout.CENTER);

        Menu.add(Hospedaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 270, 60));

        Reservaciones.setBackground(new java.awt.Color(21, 101, 192));
        Reservaciones.setMinimumSize(new java.awt.Dimension(130, 30));
        Reservaciones.setLayout(new java.awt.BorderLayout());

        reservaciones.setBackground(new java.awt.Color(21, 101, 192));
        reservaciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reservaciones.setForeground(new java.awt.Color(255, 255, 255));
        reservaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/calendar-multiple-check.png"))); // NOI18N
        reservaciones.setText("Reservaciones");
        reservaciones.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        reservaciones.setBorderPainted(false);
        reservaciones.setContentAreaFilled(false);
        reservaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reservaciones.setFocusPainted(false);
        reservaciones.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reservaciones.setIconTextGap(10);
        reservaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reservacionesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reservacionesMouseExited(evt);
            }
        });
        reservaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservacionesActionPerformed(evt);
            }
        });
        Reservaciones.add(reservaciones, java.awt.BorderLayout.CENTER);

        Menu.add(Reservaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 270, 60));

        Usuarios.setBackground(new java.awt.Color(21, 101, 192));
        Usuarios.setLayout(new java.awt.BorderLayout());

        usuarios.setBackground(new java.awt.Color(21, 101, 192));
        usuarios.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usuarios.setForeground(new java.awt.Color(255, 255, 255));
        usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/account-multiple.png"))); // NOI18N
        usuarios.setText("Usuarios");
        usuarios.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        usuarios.setBorderPainted(false);
        usuarios.setContentAreaFilled(false);
        usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        usuarios.setFocusPainted(false);
        usuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        usuarios.setIconTextGap(10);
        usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usuariosMouseExited(evt);
            }
        });
        usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosActionPerformed(evt);
            }
        });
        Usuarios.add(usuarios, java.awt.BorderLayout.CENTER);

        Menu.add(Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 270, 60));

        Reportes.setBackground(new java.awt.Color(21, 101, 192));
        Reportes.setLayout(new java.awt.BorderLayout());

        reportes.setBackground(new java.awt.Color(21, 101, 192));
        reportes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reportes.setForeground(new java.awt.Color(255, 255, 255));
        reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/file-chart.png"))); // NOI18N
        reportes.setText("Reportes");
        reportes.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        reportes.setBorderPainted(false);
        reportes.setContentAreaFilled(false);
        reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reportes.setFocusPainted(false);
        reportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reportes.setIconTextGap(10);
        reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportesMouseExited(evt);
            }
        });
        reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportesActionPerformed(evt);
            }
        });
        Reportes.add(reportes, java.awt.BorderLayout.CENTER);

        Menu.add(Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 270, 60));

        Background.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        Header.setBackground(new java.awt.Color(25, 118, 210));
        Header.setPreferredSize(new java.awt.Dimension(750, 150));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Administracion/Control/Hotel");

        dateText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        dateText.setForeground(new java.awt.Color(255, 255, 255));
        dateText.setText("Hoy es {dayname}  {day}  de {month} de {year}");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(HeaderLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateText)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        Background.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 1440, -1));

        Headerbar.setBackground(new java.awt.Color(255, 255, 255));
        Headerbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderbarMouseDragged(evt);
            }
        });
        Headerbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderbarMousePressed(evt);
            }
        });

        Exitpanel.setBackground(new java.awt.Color(255, 255, 255));
        Exitpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exitpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitpanelMouseExited(evt);
            }
        });

        Exitxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Exitxt.setText("X");
        Exitxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exitxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ExitpanelLayout = new javax.swing.GroupLayout(Exitpanel);
        Exitpanel.setLayout(ExitpanelLayout);
        ExitpanelLayout.setHorizontalGroup(
            ExitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
            .addGroup(ExitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExitpanelLayout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(Exitxt)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        ExitpanelLayout.setVerticalGroup(
            ExitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
            .addGroup(ExitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ExitpanelLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(Exitxt)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout HeaderbarLayout = new javax.swing.GroupLayout(Headerbar);
        Headerbar.setLayout(HeaderbarLayout);
        HeaderbarLayout.setHorizontalGroup(
            HeaderbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderbarLayout.createSequentialGroup()
                .addContainerGap(1002, Short.MAX_VALUE)
                .addComponent(Exitpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(635, 635, 635))
        );
        HeaderbarLayout.setVerticalGroup(
            HeaderbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Exitpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Background.add(Headerbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 1660, 30));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Background.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 750, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hospedajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospedajeActionPerformed
        ShowJPanel(new Accommodations());
    }//GEN-LAST:event_hospedajeActionPerformed

    private void PrincipalbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrincipalbtnActionPerformed
            ShowJPanel(new Principal());
    }//GEN-LAST:event_PrincipalbtnActionPerformed

    private void reservacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservacionesActionPerformed
        ShowJPanel(new Reservations());
    }//GEN-LAST:event_reservacionesActionPerformed

    private void usuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariosActionPerformed
        ShowJPanel(new Users());
    }//GEN-LAST:event_usuariosActionPerformed

    private void PrincipalbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrincipalbtnMouseEntered
        Principalbtn.setBackground(new Color(0,102 ,255 ));
        Principal.setBackground(new Color(0,102 ,255 )); 
    }//GEN-LAST:event_PrincipalbtnMouseEntered

    private void PrincipalbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrincipalbtnMouseExited
       Principalbtn.setBackground(new Color(21,101 ,192 ));
       Principal.setBackground(new Color(21,101 ,192 ));
      
    }//GEN-LAST:event_PrincipalbtnMouseExited

    private void hospedajeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospedajeMouseEntered
        hospedaje.setBackground(new Color(0,102 ,255 ));
        Hospedaje.setBackground(new Color(0,102 ,255 ));
    }//GEN-LAST:event_hospedajeMouseEntered

    private void hospedajeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hospedajeMouseExited
        hospedaje.setBackground(new Color(21,101 ,192 ));
        Hospedaje.setBackground(new Color(21,101 ,192 ));
    }//GEN-LAST:event_hospedajeMouseExited

    private void reservacionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservacionesMouseEntered
        reservaciones.setBackground(new Color(0,102 ,255 ));
        Reservaciones.setBackground(new Color(0,102 ,255 ));
    }//GEN-LAST:event_reservacionesMouseEntered

    private void reservacionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservacionesMouseExited
        reservaciones.setBackground(new Color(21,101 ,192 ));
        Reservaciones.setBackground(new Color(21,101 ,192 ));
    }//GEN-LAST:event_reservacionesMouseExited

    private void usuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariosMouseEntered
        usuarios.setBackground(new Color(0,102 ,255 ));
        Usuarios.setBackground(new Color(0,102 ,255 ));
    }//GEN-LAST:event_usuariosMouseEntered

    private void usuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuariosMouseExited
        usuarios.setBackground(new Color(21,101 ,192 ));
        Usuarios.setBackground(new Color(21,101 ,192 ));
    }//GEN-LAST:event_usuariosMouseExited

    private void reportesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportesMouseEntered
        reportes.setBackground(new Color(0,102 ,255 ));
        Reportes.setBackground(new Color(0,102 ,255 ));
    }//GEN-LAST:event_reportesMouseEntered

    private void reportesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportesMouseExited
        reportes.setBackground(new Color(21,101 ,192 ));
        Reportes.setBackground(new Color(21,101 ,192 ));
    }//GEN-LAST:event_reportesMouseExited

    private void ExitxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitxtMouseClicked

    private void HeaderbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderbarMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderbarMousePressed

    private void HeaderbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderbarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HeaderbarMouseDragged

    private void ExitpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitpanelMouseEntered
        Exitpanel.setBackground(Color.red);
        Exitxt.setForeground(Color.white);
    }//GEN-LAST:event_ExitpanelMouseEntered

    private void ExitpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitpanelMouseExited
        Exitpanel.setBackground(Color.white);
        Exitxt.setForeground(Color.black);
    }//GEN-LAST:event_ExitpanelMouseExited

    private void ExitxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitxtMouseEntered
        Exitpanel.setBackground(Color.red);
        Exitxt.setForeground(Color.white);
    }//GEN-LAST:event_ExitxtMouseEntered

    private void ExitxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitxtMouseExited
        Exitpanel.setBackground(Color.white);
        Exitxt.setForeground(Color.black);
    }//GEN-LAST:event_ExitxtMouseExited

    private void ExitpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitpanelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitpanelMouseClicked

    private void reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportesActionPerformed
       ShowJPanel(new Reports());
    }//GEN-LAST:event_reportesActionPerformed
    
    private void SetDate(){
        LocalDate now = LocalDate.now();
        Locale spanishLocale = new Locale("es", "ES");
        dateText.setText(now.format(DateTimeFormatter.ofPattern("'Hoy es' EEEE dd 'de' MMMM 'de' yyyy", spanishLocale)));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Exitpanel;
    private javax.swing.JLabel Exitxt;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Headerbar;
    private javax.swing.JPanel Hospedaje;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Principal;
    private javax.swing.JButton Principalbtn;
    private javax.swing.JPanel Reportes;
    private javax.swing.JPanel Reservaciones;
    private javax.swing.JPanel Usuarios;
    public static javax.swing.JPanel content;
    private javax.swing.JLabel dateText;
    private javax.swing.JButton hospedaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton reportes;
    private javax.swing.JButton reservaciones;
    private javax.swing.JButton usuarios;
    // End of variables declaration//GEN-END:variables
}
